<section class="section container">
	<div class="sectionHeading">Research</div>
	<div class="sectionHeading">Global Collaborations</div>
	<div class="sectionContent">
		<p>Enabled by JECRC Foundationâ€™s collaboration with the University of Alabama, an Immersive Visualization Laboratory has been set up at JECRC to facilitate students in taking up forward thinking projects and research in immersive visualization, scientific visualization, art, psychology and cognition. Dr. Philip Oldham, President, Tennessee Tech University and Dr. Bharat Soni, VP, Research and Economic Development, Tennessee Tech University visited JECRC Foundation to discuss the possibility of an academic collaboration between the two organizations. Dr. Oldham greatly appreciated the Research Labs, Social Initiatives, Aircraft Models and ATVs at JECRC. The International Association for Exchange of Students for furthering Technical Experience (IAESTE) has provided students with more than 40 paid internships abroad in reputed establishments.</p>
	</div>
	<div class="sectionHeading">
		Research & Development
	</div>
	<div class="sectionContent">
		<p>Financial support has been obtained from various funding agencies like the Department of Science & Technology, Govt. of India, All India Council for Technical Education and others, for a number of R&D projects. The total funding exceeds Rs. 1 Crore. Three R&D projects from DST have been completed and reports submitted to the full satisfaction of DST. A large number of student projects has been funded by The Department of Science & Technology, Rajasthan. An exhibition of 55 selected projects was organized in which the Director (DST) showed keen interest and appreciation for the completed projects. The mission of the CSI is to facilitate research, knowledge sharing, learning and career enhancement for all categories of IT professionals, while simultaneously inspiring and nurturing new entrants into the industry and helping them to integrate into the IT community. The CSI is also working closely with other industry associations, government bodies and academia to ensure that the benefits of IT advancement ultimately percolate down to every single citizen of India. In 2017-18, JECRC faculty published more than 200 papers in various national and international journals and proceedings of International and National conferences organized by reputed institutes. Validation and scientific basis of â€˜Meditation and Omnics to cure various diseases and their role as therapeutic targetsâ€™ has been approved for Rs. 45 Lacs funding by Department of Science and Technology, Govt. of India. JECRC is developing a Meditation research lab which will help students and staff to work on physical and metaphysical aspects of the human mind.</p>
	</div>
</section>