<section id="news" class="container card section">
	<div class="sectionHeading">Latest from ECE Department</div>
	<div class="card-body sectionContent ">
<ul class="sectionList">
<li class="bullet">Faculty Development Program (FDP)-Software Engineering Modeling tools  technology
<p><strong>Objective:</strong>To enhance the knowledge of faculty  students to design  conduct software Engineering experiments, knowledge of modern Engineering tools  technology as well as to analyze and interpret the data<strong>.</strong></p>
<p><strong>Outcome:</strong></p>
<p>Faculty will be able to:</p>
<p>1. In-corporate different designing  modeling tools that would be helpful in teaching students.</p>
<p>2. Analyze, Design, implement and maintain software systems.</p>
<p>3. Use modern engineering tools required for various Engineering practices.</p>
<br />Posted on: 2018-02-03</li>
<li class="bullet">Expert Talk on Awareness on Cyber Crimes in social media  Introduction to forensic science on 23rd Sep-17 delivered by Dr. Deepak Raj Rao<br />Posted on: 2017-09-23</li>
<li class="bullet">Department of CSE Organized a 2 days workshop on Cyber Security in association with AKTU and UP Police from 20-21st September 17.Expert Mr. Rahul Mishra<br />Posted on: 2017-09-20</li>
<li class="bullet">Short Term Course on Scilab Programming (Through ICT mode) by NITTTR, Chandigarh from 24-28 July 2017.<br />Posted on: 2017-07-24</li>
<li class="bullet">AMMTP-2013The workshop Advances in Multimodal Multilingual Translation aims at presenting and discussing the technology, results and possibilities of the SEECAT prototype in an Indian context, and to examine future avenues in multimodal translation. Participants of the SEECAT summer 2013 project will present their work and invited speakers from academia, companies and government will discuss future directions in education and industry.<br />Posted on: 2015-04-08</li>
<li class="bullet">Mobipreneur Workshop 	 CompetitionNurture Talent Academy has conducted two days workshop on "Mobipreneur Workshop  Competition" in association with CSI under the event TECHHUNT 2014 at JSSATE, Campus. Trainer Mr. Praveen Samariya and Mr. Ravi have given the exposure of mobile computing and its application development using technology "ANDROID" to the participants. One team has been selected and awarded achievement certificate for further rounds at National Level. Participation certificates and coordination certificates were also distributed to other students on behalf of CSI.<br />Posted on: 2015-04-08</li>
<li class="bullet">Soft Computing  Applications SCA-14A workshop on &ldquoSoft computing and Applications SCA&rsquo14&rdquo was successfully held at JSSATE, Noida in collaboration with Center for Soft Computing Research (An Associate Institution of ISI) Indian Statistical Institute, Kolkata from 2<sup>nd</sup>- 4<sup>th</sup>September,2014. There were nine eminent speakers from all over the nation who covered all the recent research issues on soft computing and its applications. The total participants registered for the workshop were 63 including academicians,research scholars, decision makers from the industry working in the fields of Information Technology,Computer Science, Electronics  Communication Engineering, Electrical Engineering and other science related field. The keynote speaker Padamshree Dr.Sankar K.Pal from ISI Kolkatta was the chief guest of the event. The workshop had many distinguished speakers Prof. Ashish Ghosh, Prof. C.A.Murthy, Prof. B.Chanda, Prof. Sushmita Mitra from ISI Kolkatta, Dr. P.Nagabhushan from University of Mysore, Prof. B.Ravindran from IIT Madras, Prof. Shirish Shevade from IISc Bangalore and Dr. T.N. Nagabhushan, Principal,JSSATE Noida .<br />Posted on: 2014-09-04</li>
<li class="bullet">Seminar on "Current IT Trends for 2014" on CSI-DayAn invited talk on "IT Trends for 2014" by Mr. Amit Grover, CEO and Founder Nurture Talent has been delivered on the occasion of CSI-day to student members of CSI and faculty members of JSS Academy of Technical Education, Noida which is organized by JSSATE-CSI-Student Branch. Besides highlighting IT trends, he advised the students to try to achieve expertise in different application domains and fulfil their social responsibilities.<br />Posted on: 2014-04-08</li>
<li class="bullet">Windows Phone App Workshop on 26 March,27 March 2014A workshop on "Windows Phone App" development was conducted with the focus on building applications for Windows Phone 7.x , 8.0 and 8.1 devices<br />Posted on: 2014-03-26</li>
<li class="bullet">Inauguragtion of Student Branch-CSI at JSSATE, Noida CampusCSI Student Branch was inaugurated at JSS Academy of Technical Education, Noida on 25th February 2014. Prof. R.K. Vyas, Vice president Region-1 gave inaugural address and the chief guest Dr. Gulshan Rai Director General - ICERT, Ministry of Communication and Information Technology delivered the keynote address on "Cyber Space- Emerging Cyber Crimes and Threats".<br />Posted on: 2014-02-25</li>
<li class="bullet">Nokia: IPR / IWN Workshop on 7th August 2013<br />Posted on: 2013-08-07</li>
<li class="bullet">Mobile Innovation Workshop 2013Three days Nokia hands on workshop was being organized from 29th September-1st October 2013.The day one training was for Feature phones / entry level smart phones(Nokia Asha) using J2ME.The day two training focussed on Smart phones &acirc&euro&ldquo Windows phone OS(Nokia Lumia) using C#. On last day students supposed to design one full fledged Asha application and onefull fledged Windows phone application.<br />Posted on: 2013-04-08</li>
</ul>
</div>
</section>