<section class="section container">
	<div class="sectionHeading">Companies Visit Our Campus</div>
	<div class="row">
		<div class="col-md-4">
			<ul class="list-group list-group-flush">
				<li class="list-group-item">Accenture</li>
				<li class="list-group-item">Capgemini</li>
				<li class="list-group-item">Pinnacle</li>
				<li class="list-group-item">TCS CodeVita</li>
				<li class="list-group-item">TCS Ninja Final</li>
				<li class="list-group-item">BYJU</li>
				<li class="list-group-item">Mindtree</li>
				<li class="list-group-item">Intime Tec</li>
				<li class="list-group-item">Info Object</li>
				<li class="list-group-item">Mechlan Technology</li>
				<li class="list-group-item">Trading Bells</li>
				<li class="list-group-item">Sopra Steria</li>
				<li class="list-group-item">Helois Web Services</li>
				<li class="list-group-item">Linkruit</li>
				<li class="list-group-item">Just Dial</li>
				<li class="list-group-item">Pin Click</li>
				<li class="list-group-item">Academia Guru</li>
				<li class="list-group-item">Gulati auto Electricals</li>
				<li class="list-group-item">Smart circle group</li>
				<li class="list-group-item">Ongraph</li>
				<li class="list-group-item">Thrillophilia</li>
				<li class="list-group-item">Scope Telecom Pvt. Ltd.</li>
				<li class="list-group-item">Appeal Group</li>
				<li class="list-group-item">ENC technology</li>
				<li class="list-group-item">Aquatronic systems</li>
				<li class="list-group-item">JRBS</li>
				<li class="list-group-item">Accenture</li>
				<li class="list-group-item">Cause Code</li>
				<li class="list-group-item">TCS</li>
				<li class="list-group-item">Pinnacle Infotech</li>
				<li class="list-group-item">Artech Infosystem</li>
				<li class="list-group-item">Newgen Software</li>
				<li class="list-group-item">Matrix ComSec</li>
				<li class="list-group-item">InfoObjects</li>
				<li class="list-group-item">Auriga IT</li>
				<li class="list-group-item">HexaView Technologies</li>
				<li class="list-group-item">Skill Rockk Technologies</li>
				<li class="list-group-item">App_perfect</li>
				<li class="list-group-item">EnY</li>
				<li class="list-group-item">Zycus</li>
				<li class="list-group-item">Genus Power</li>
				<li class="list-group-item">Matrix (phase 2)</li>
				<li class="list-group-item">Matrix (Phase 3)</li>
				<li class="list-group-item">Josh Technology</li>
				<li class="list-group-item">Toppr</li>
				<li class="list-group-item">BY JUs</li>
				<li class="list-group-item">IBM</li>
				<li class="list-group-item">TCS (interns)</li>
				<li class="list-group-item">TCS Pool Campus</li>
				<li class="list-group-item">Sopra</li>
				<li class="list-group-item">GKM-IT</li>
				<li class="list-group-item">RMC</li>
				<li class="list-group-item">Kotak Life Insurance</li>
				<li class="list-group-item">ATCS</li>
			</ul>
		</div>
		<div class="col-md-4">
			<ul class="list-group list-group-flush">
				<li class="list-group-item">Metacube</li>
				<li class="list-group-item">FACE</li>
				<li class="list-group-item">NIIT Tech</li>
				<li class="list-group-item">GuruKripa</li>
				<li class="list-group-item">Best Peers</li>
				<li class="list-group-item">SimplyForce</li>
				<li class="list-group-item">FEV India</li>
				<li class="list-group-item">HSBC</li>
				<li class="list-group-item">Think & Quant (Sports)</li>
				<li class="list-group-item">21 Fools</li>
				<li class="list-group-item">Marketing Mindz</li>
				<li class="list-group-item">Hexawre Technology</li>
				<li class="list-group-item">Liugong India</li>
				<li class="list-group-item">GR Infra</li>
				<li class="list-group-item">ARN Focus IIT</li>
				<li class="list-group-item">Metacube Software 2</li>
				<li class="list-group-item">Ericcson</li>
				<li class="list-group-item">Capegemini</li>
				<li class="list-group-item">Gensus Edutainers</li>
				<li class="list-group-item">JPPL</li>
				<li class="list-group-item">Human Horizon</li>
				<li class="list-group-item">Pal IT Services</li>
				<li class="list-group-item">Interview Air</li>
				<li class="list-group-item">Capital Trust</li>
				<li class="list-group-item">Dev Technosys</li>
				<li class="list-group-item">Mind IT Promotions</li>
				<li class="list-group-item">Talent Pull</li>
				<li class="list-group-item">Sworntech Pvt. Ltd.</li>
				<li class="list-group-item">Skyway Infosolutios</li>
				<li class="list-group-item">ZumoSun International Research & Consultancy (India) Pvt. Ltd.</li>
				<li class="list-group-item">Saajha Constructions</li>
				<li class="list-group-item">Kapiashwar Infracon Pvt. Ltd.</li>
				<li class="list-group-item">TATA Technologies</li>
				<li class="list-group-item">SLK Technologies</li>
				<li class="list-group-item">Voylla</li>
				<li class="list-group-item">Adnate</li>
				<li class="list-group-item">Capital Via</li>
				<li class="list-group-item">Anora Lab</li>
				<li class="list-group-item">First American</li>
				<li class="list-group-item">Skill Rock Tech</li>
				<li class="list-group-item">Horizon InfraDesign</li>
				<li class="list-group-item">Ashiana Housing</li>
				<li class="list-group-item">Nodd Technologies</li>
				<li class="list-group-item">Sopra Steria</li>
				<li class="list-group-item">Techno Copacetic</li>
				<li class="list-group-item">HP</li>
				<li class="list-group-item">Bulls Eye</li>
				<li class="list-group-item">JUSPAY</li>
				<li class="list-group-item">TechieNest</li>
				<li class="list-group-item">Techfleeters</li>
				<li class="list-group-item">JK Cement</li>
				<li class="list-group-item">KAI Manufactures</li>
				<li class="list-group-item">Oppo Mobiles</li>
			</ul>
		</div>
		<div class="col-md-4">
			<ul class="list-group list-group-flush">
				<li class="list-group-item">CalSoft</li>
				<li class="list-group-item">Adani Power</li>
				<li class="list-group-item">Bridgestone</li>
				<li class="list-group-item">Ericsson</li>
				<li class="list-group-item">Bhilwara Infotech</li>
				<li class="list-group-item">TechAhead</li>
				<li class="list-group-item">Adobe System</li>
				<li class="list-group-item">HLS Asia</li>
				<li class="list-group-item">TIPL</li>
				<li class="list-group-item">Product Lab</li>
				<li class="list-group-item">Coders Brain Technology</li>
				<li class="list-group-item">Aayat Softech Pvt Ltd.</li>
				<li class="list-group-item">Lantern's Info</li>
				<li class="list-group-item">System Pvt. Ltd.</li>
				<li class="list-group-item">Horizon</li>
				<li class="list-group-item">GIPL</li>
				<li class="list-group-item">MIND IT</li>
				<li class="list-group-item">Ramma Greens</li>
				<li class="list-group-item">DLB Infotech</li>
				<li class="list-group-item">GENSUS Design</li>
				<li class="list-group-item">Appcino Technology</li>
				<li class="list-group-item">Vaahika</li>
				<li class="list-group-item">Tata Consultancy Service</li>
				<li class="list-group-item">Accenture Services Pvt Ltd.</li>
				<li class="list-group-item">Rebuscode</li>
				<li class="list-group-item">Tata Technologies Ltd.</li>
				<li class="list-group-item">Saint Gobain</li>
				<li class="list-group-item">ConfigAware</li>
				<li class="list-group-item">Info-Objects</li>
				<li class="list-group-item">AppPerfect</li>
				<li class="list-group-item">Persistent Soft</li>
				<li class="list-group-item">First American Company</li>
				<li class="list-group-item">Genpact</li>
				<li class="list-group-item">Capegemini</li>
				<li class="list-group-item">Skill Rock Technologies</li>
				<li class="list-group-item">Adani group</li>
				<li class="list-group-item">Idea Cellular</li>
				<li class="list-group-item">Bluecubes</li>
				<li class="list-group-item">TCS Off Campus</li>
				<li class="list-group-item">NCR Group</li>
				<li class="list-group-item">PRS Associates LLP</li>
				<li class="list-group-item">Tech Mahindra</li>
				<li class="list-group-item">Vodafone</li>
				<li class="list-group-item">Arc Gate</li>
				<li class="list-group-item">Samsung Research</li>
				<li class="list-group-item">Microsoft (off campus)</li>
				<li class="list-group-item">Phone Support</li>
				<li class="list-group-item">Teleperformace</li>
				<li class="list-group-item">Dewan solutions</li>
				<li class="list-group-item">IKY</li>
			</ul>
		</div>
	</div>
	<div class="sectionContent">
	</div>
</section>