<section class="section container">
	<div class="sectionHeading">Alumni Connect</div>
	<div class="sectionContent">
		<div class="col-12 text-center my-3">
			<img src="../departments/alumni/src/img/alma_connect.png" alt="alumni connect" class="img-fluid center">
		</div>
		<p>JECRC has a strong base of 9000+ Alumni stationed at various locations across the globe doing pretty well in their respective fields. The JECRC alumni association cell has been established with the prime objective of strengthening the Alma bonds with a larger perspective to inculcate a culture where the alumni and the present students of the college can be made to interact with each other leading to an ecosystem of multidimensional growth and future prospects the institution values relationships and our association with student is a lifelong bond. The college organizes regular interactive sessions with the alumni and the present students on “entrepreneurship” and “grooming of the student” to prepare them for the corporate challenges that confront them. JECRC already has 150+ alumni start ups that have not only established themselves well but also assist in placements and internships for the present students. The vertical has organized several events and activities like “Meet and greet sessions” where the students get to interact with the Alumni from various countries and fields and get their questions answered, The College also organized “Alumni Start-up Meet” and regularly organizes “Chapter meets”.</p>
		<p>During the annual fest of the college, Renaissance, the alumni are especially invited to re-connect in the college and renew their bonds. This year the college witnessed the second edition of alumni vs. faculty cricket match with huge success.</p>
		<p>Alumni from across the world provide many opportunities such as placements and internship in their startups and as well as in their companies they are working with.Many more initiatives are in the process, for the mutual growth development of alumni, students and the Alma-Mater at large.</p>
	</div>
</section>