<section class="section container">
	<div class="sectionHeading">Entrepreneurship Ecosystem</div>
	<div class="sectionContent">
		<p>Entrepreneurship in India is yet to reveal it’s hidden potential. It will not only help India to frontier with the world leaders but also unlock the quality of brains that we are so proud of. With this idea JECRC wishes to inculcate and enrich the entrepreneurial environment in the campus and the country at large by creating an easily accessible and exhaustive set of resources for the entrepreneurs, which including the students, the budding professionals, mentors, the angel</p>
		<p>investors and the venture capitalists through various fun filled yet educating sessions such as start-up meets, competitions, etalks and so on and so forth JECRC believes that entrepreneurship is not just about starting companies, but a pathway</p>
		<p>towards India’s socio-economic development. Our vision is to make students and faculty ‘entrepreneurial’ in every work that they do. We hope to enable them to solve global challenges as we see students as the greatest capital and intend to nurture them, provide them with opportunities for excellence.</p>
		<p>The Incubation center by JECRC strives hard to make the students entrepreneurial journey smooth and infuse the spirit of entrepreneurship among others.</p>
		<p>It aims to unlock students’ latent inventive potential. Not only do we show the doors of opportunity but we also equip to walk through it. Through our conference, social events, lectures, speaker engagements and workshops, we&#39;re hoping to bring together everyone interested in the startup world and to help students best utilize resources to found or join startups.</p>
		<p>And the best example of the support that JECRC provides by always being the cushion in the entrepreneurial journey of its students can be very well seen from the larger number of alumni who have gone out of the box and started their own start ups which deal with a variety of fields ranging from manufacturing of Jaipur Belt to being the producer of movies. With more than 150 alumni start ups JECRC stands high to provide guidance to it’s present students by organizing talks between present CEOs , founders and the budding Founders, that quenches lot of budding answers and gives birth to new ideations simultaneously. What can be better than hearing it from the ones who have been on the same boat and sailed it to nooks of the world yet to be explored by others.</p>
	</div>
</section>