<section class="section container">
	<div class="sectionHeading">Student Development and Initiatives</div>
	<div class="sectionContent">
		<div class="sectionSubHeading">Entrepreneurship Development Cell</div> 
<div class="sectionContent">The Entrepreneurship Development Cell organised various programmes in the previous year to enhance entrepreneurship skills in the students of JECRC Foundation. Some of these programmes are Entrepreneurship Awareness Programme, Entrepreneurship Development Programme, Skill Development Programme, Business Development Programme in Export Marketing, Entrepreneurship Awareness Camp, B-Guru, Industrial Visit, Faculty Training etc. </div>
<div class="sectionSubHeading">IBM The Great Mind Challenge Contest</div>
<div class="sectionContent">Students of all branches got industry exposure by visiting 14 industries in the previous year. A programme on personality development was launched for IIPC students & another programme on advanced multimedia was organised under Competency Development Programme of IIPC. Specialised talks from various industry experts were held last year. Wipro is actively associated with the IIPC of JECRC.</div>
<div class="sectionSubHeading">Industry Institute Partnership Cell (IIPC)</div>
<div class="sectionContent">This is an initiative to keep our students in sync with the latest tools and technologies. It provides a platform for students to extract benefits from various workshops and seminars on new technologies from world leaders like IBM.</div>


<div class="sectionSubHeading">Infosys Campus Connect </div>
<div class="sectionContent">This academic year, JECRC successfully rolled-out Campus Connect Program of Infosys Technologies Ltd., a unique academia-industry initiative, for more than 100 final year students to align them towards the competencies which industry needs and thus increases their chances of employability. Under the aegis of this initiative, students and faculty members are privileged to access courseware and technology relevant to the current scenario of IT industry. This is an annual feature at JECRC. </div>
<div class="sectionSubHeading">TCS Flagship Events </div>
<div class="sectionContent">JECRC takes pride in standing with highest registrations in TCS Flagship events namely, Codevita and Testimony from the north region. These events have paved way for students to get an edge over their skill-set. Students have shown sincere interest into the events and outshone with their performance, consequently leading to fruitful internships with the industry which has been rated as the World's most powerful brand in IT Services for the year 2017.</div>
<div class="sectionSubHeading">ISRO Exhibition</div>
<div class="sectionContent">For the second consecutive year an exhibition was organized in Rajasthan by the INDIAN SPACE RESEARCH ORGANISATION - Exhibition and Outreach Division, in JECRC University, Jaipur on 19th-20th April 2018, with a view to increase the awareness of science and technology among students. This exhibition displayed models and latest technologies related to spacecraft, launch vehicle, rockets and other technologies developed by ISRO. Launch of mini satellites (water launch) were performed live. In addition, ISRO conducted a one student interaction program, quiz program and debate. Many prominent scientists from ISRO graced this occasion and delivered expert lectures on launch vehicles, satellites, applications and future technologies.</div>
<div class="sectionSubHeading">Training for Civil Services</div>

<div class="sectionContent">Under the guidance of Retd. IRS Sh. M. L. Sharma, Vice Chairman, JECRC, Retd. IRS Sh. O.P. Jain, Senior Advisor, JECRC & former DGP, Rajasthan Sh. P. K. Tiwari students are not just motivated but also provided proper training to aspire for the coveted civil services examination. Mock interviews are conducted for the aspiring students to prepare them mentally for the rigorous examination. As a result many of our students have been able to crack the civil services examination. Srishti Jain, Batch 2015, RAS Rank 152, Shivam Joshi, Batch 2016, RAS Rank 316, Pushpendra Deshwal, Batch 2014, RAS Rank 271 and Mrityunjay Mishra, Batch 2010, RAS Rank 12 are few of the names.</div>

<div class="sectionSubHeading">IAESTE</div>
IAESTE is an independent, non-profit, non-political and non-governmental international association that deals with the exchange of students for technical experience. Student pursuing technical education (particularly in science, engineering and the applied arts) are provided with opportunities to apply for paid, course-related, training abroad. With over 80 countries involved and exchanging over 7000 job offers search year worldwide, it is the largest organization of its kind in the world, affecting around 3,35,000 students since its inception. IAESTE provides students with a unique opportunity to gain relevant technical training that lasts from 4-52 weeks. IAESTE India LC JECRC is the flagship student exchange programme of JECRC UNIVERSITY running from the past 4 years. 
