<section class="section container">
	<div class="sectionHeading">Our Industrial Liaisons</div>
	<div class="sectionSubHeading">
		Tata Consultancy Services
	</div>
	<div class="sectionContent">
		<p>JECRC stands accredited by Tata Consultancy Services for recruitment purposes. We are active members of AIP. We make sure that all our students are members of Campus commune and participate in all competitions and activities under it. Our students have participated in highest numbers among colleges across North India in all activities under campus commune such as Code Vita, Testimony, ENGinex, DISQ etc. Many students get selected through these competitions. Ten of our students have been selected for the DISQ Program of TCS. Many of our students have been selected for remote internships also and later to the company because of excellent performance during their remote internships.</p>
	</div>
	<div class="sectionSubHeading">Ericsson</div>
	<div class="sectionContent">
		<p>Ericsson conducts Telecom Essential Training for students under Career Connect program. Experts from telecom industry train 50 students in a batch every year in telecom domain. Students are trained bout mobile networking, present and future technologies in the field of telecom. The training also covers fundaments of internet through mobile. The real-life problems and solutions to the problems, shared by the industry experts add to skills and knowledge of students beyond the learning from books. After the training students have to appear for the test to get certified for the training. The training has helped students during the recruitment by the telecom companies. This resulted in recruitment of about 20 students from JECRC.</p>
	</div>
	<div class="sectionSubHeading">Pinnacle InfoTech</div>
	<div class="sectionContent">
		<p>Pinnacle InfoTech organizes specialized training in CAD, CAM, BIM Technology etc for our students at JECRC. This has resulted in recruitment of about 100 students from JECRC Foundation. This year Pinnacle Infotech has chosen JECRC College as Corporate Training Centre not only for JECRC students but for students selected from other colleges of region too. All the offered candidates have undergone in 2 months rigorous training by their domain experts. Microsoft First Microsoft Innovation i-spark centre in Northern India. Microsoft Ed-Vantage: JECRC Foundation is a Platinum level member of Microsoft Ed- Vantage Program. This program facilitates students through technology sessions and workshops by experts along with offering opportunities for internships and employability to the bright students. A good number of our students are certified as Technology Associates, Office Specialists as well as Solution Associates &amp; Developers under this program. Apart from this, our faculty members have also marked their presence on Microsoft Educator Network as Innovative Faculty, 2015 and are able to publish their work on their portal.</p>
	</div>
	<div class="sectionSubHeading">IBM</div>
	<div class="sectionContent">
		<p>IBM has established software centre for excellence fully equipped with IBM Technologies software, courseware and other educational resources. We have conducted many training programs on IBM tools. Many students are getting certified on these tools every year. Faculty members have been trained on Rational Unified process tools and they in turn impart training to students. Our students have been taking part and winning prizes in “The great Mind Challenge “contest organized by IBM.</p>
	</div>
	<div class="sectionSubHeading">Start Up Ecosystem at JECRC</div>
	<div class="sectionContent">
		<p>Entrepreneurship in India is yet to reveal it’s hidden potential. It will not only help India to frontier with the world leaders but also unlock the quality of brains that we are so proud of. With this idea JECRC wishes to inculcate and enrich the entrepreneurial environment in the campus and the country at large by creating an easily accessible and exhaustive set of resources for the entrepreneurs, which including the students, the budding professionals, mentors, the angel investors and the venture capitalists through various fun filled yet educating sessions such as start-up meets, competitions, etalks and so on and so forth JECRC believes that entrepreneurship is not just about starting companies, but a pathway towards India’s socio-economic development. Our vision is to make students and faculty ‘entrepreneurial’ in every work that they do. We hope to enable them to solve global challengesas we see students as the greatest capital and intend to nurture them, provide them with opportunities for excellence. The Incubation center by JECRC strives hard to make the students entrepreneurial journey smooth and infuse the spirit of entrepreneurship among others. It aims to unlock students’ latent inventive potential. Not only do we show the doors of opportunity but we also equip to walk through it. Through our conference, social events, lectures,speaker engagements and workshops, we&#39;re hoping to bring together everyone interested in the startup world and to help students best utilize resources to found or join startups. And the best example of the support that JECRC provides by always being the cushion in the entrepreneurial journey of its students can be very well seen from the larger number of alumni who have gone out of the box and started their own start ups which deal with a variety of fields ranging from manufacturing of Jaipur Belt to being the producer of movies. With more than 150 alumni start ups JECRC stands high to provide guidance to it’s present students by organizing talks between present CEOs , founders and the budding Founders, that quenches lot of budding answers and gives birth to new ideations simultaneously. What can be better than hearing it from the ones who have been on the same boat and sailed it to nooks of the world yet to be explored by others.</p>
	</div>
</section>