<div id="academics" class="container card section">
<div class="sectionHeading">About</div>
<p class="px-4">
Civil engineering is a professional engineering discipline that deals with the design, construction and maintenance of the physical and naturally built environment, including works like roads, bridges, canal, damns and building. Civil engineering is traditionally broken into a number of sub-disciplines. It is the second oldest engineering discipline after military engineering, and it is defined to distinguish non military engineering and military engineering. Civil engineering takes place in the public sector from municipal through to national governments, and in the private sector from individual homeowners through to international companies.
‘Jaipur engineering college and research centre, Jaipur’ was established in 2000 and the Civil engineering department is the part of the institute. The department has grown tremendously over the years and in now recognized as one of the major engineering departments in the country. The department has developed strong links with the building and construction industry and academic and research in the country. The department of civil engineering with its multifaceted faculty continues to maintain and cultivate its strong links with the infrastructural industry and academic in the country.
Civil engineering departments works on a mission to provide outcome based education to create a learning environment conducive for achieving academic excellence and to prepare civil engineers for the society with high ethical values. Also, the vision of institute of is to become a renowed centre of outcome based learning and work towards academic, professional, cultural and social enrichment of the lives of individuals and communities.
Civil engineering being one of the core and most fundamental engineering branches is fully dedicated towards the same teaching and learning philosophy of foundation with a team of dozen and highly qualified and experienced faculty members we offer the most enjoyable and effective learning to all the  students.
 For better understanding and effective learning of students, institute conduct many industrial and educational visit such as an educational visit to “Jantar Mantar” and sewage treatment plant visit with an endeavor to promote scientific attitude among the young minds, J-Techtrix was conducted. This project exhibition focuses on encouraging the innovations within them. The key objective is to bring out the hidden talents and inculcate technical knowledge in students.
The mission of the institute is to focus on envalution of learning outcomes and motivate students to inculcate research aptitude by project based learning, to offer opportunities for interaction between academia and industry and to develop human potential to its fullest extent so that intellectually capable and imaginatively gifted leaders may emerge.
</p>
</div>