<section class="section container card">
	<div class="sectionHeading">About</div>
	<div class="sectionContent card-body px-4">
		<p>The Department of Computer Science and Engineering (CSE), established in the 1998, is one of the oldest departments of the institution. The faculty members and technical staff are involved, not only, in classroom teaching, but also in Project Guidance, Industrial Interactions, Research Activities, Seminars, Workshops, various co-curricular activities and beyond curriculum training, aiding in the holistic development of the students.</p>
		<p>It offers a four year degree programme in Computer Science and Engineering with an annual intake of 120 students and two year M.Tech. Post Graduate programme in Computer Science with an annual intake of 18 students. These programmes are affiliated to Uttar Pradesh Technical University, Lucknow (UPTU).</p>
		<p>The state-of-the-art laboratories are equipped with latest configuration hardware and software. Although, emphasis is given on use and promotion of open source software and systems, laboratories are also equipped with proprietary software such as Rational Software Architect, Rational Functional Tester and Rational Quality Manager. The labs are Internet enabled through LAN and Wi-fi. These facilities are effectively used, not only by the faculty for the purpose of teaching, but also by the students' Nibble Computer Society for holding technical events such as quizzes, workshops and competitive events.</p>
		<p>The faculty is well qualified and a large of the faculty members are pursuing PhD from renowned institutions and are involved in research in areas such as Artificial Intelligence, Neural Network, Pattern Recognition, Natural Language Processing, Data Mining, Data Compression, Image Processing, etc. After completing the four year degree programme, most students get placed in reputed companies like Infosys, Tech Mahindra, Birlasoft, to name a few. Many students have also been hired by PSUâ€™s like Indian Navy, Indian Army and Air force, while many are pursuing M.Tech., MBA & MS from premier institutions like IISc, IITs , IIMs and Symbiosis.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita doloremque ducimus autem facilis consectetur. Vel voluptatem ex iusto nulla, quibusdam reprehenderit, impedit dolorum pariatur, eveniet rerum sequi voluptates similique nemo.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint similique expedita ullam fuga eaque officia labore possimus totam, quasi animi vero voluptatem non molestias accusamus consequatur maiores nam eligendi doloribus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum deserunt fuga dolorum nulla esse eaque perferendis unde itaque aperiam officia inventore saepe ab est, earum, dolore nihil! Unde, quam iure.</p>
	</div>
</section>